routes/web.php
<?php
use App\CountryTags;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/tags.json', function(){
	return CountryTags::get();
});

Route::get('importTest', 'ModController@test');

//User Related
Route::get('/users', 'UserController@list');
Route::get('/users/{id}', 'UserController@view');
Route::get('/account', 'UserController@account');
Route::post('/account', 'UserController@updateAccount');
Route::get('/account/media', 'UserController@media');
Route::post('/account/media', 'UserController@mediaAction');
Route::get('/notifications', 'UserController@notifications');

//Mod Related
Route::get('/mod', 'ModController@list');
Route::get('/mod/{id}', 'ModController@view');
Route::post('/mod/{id}', 'ModController@editMod');
Route::get('/mod/{id}/export', 'ModController@export');
Route::post('/mod/{id}/delete', 'ModController@delete');

//Misc Tool Related
Route::get('/flag/', 'FlagController@viewCreate');
Route::post('/flag/create', ['as' => 'flag.create', 'uses' => 'FlagController@create']);
Route::post('/flag/download/{size}', ['as' => 'flag.download', 'uses' => 'FlagController@download']);

//Builder Related
Route::post('/builder', ['as' => 'builder.search', 'uses' => 'OutcomeController@search']);

//Focus Tree Related
Route::get('/focus-tree','FocusTreeController@list');
Route::get('/focus-tree/view/{id}','FocusTreeController@view');
Route::get('/focus-tree/delete/{id}','FocusTreeController@delete');
Route::get('/focus-tree/edit/{id}',['as' => 'tree.edit', 'uses' => 'FocusTreeController@edit']);
Route::get('/focus-tree/create','FocusTreeController@showCreate');
Route::post('/focus-tree/create','FocusTreeController@createFocusTree');
Route::post('/focus-tree/edit/{id}/add','FocusTreeController@createNewFocus');
Route::post('/focus-tree/edit/{id}/edit/{focus}','FocusTreeController@editFocus');
Route::post('/focus-tree/quickedit/{id}/edit/{focus}','FocusTreeController@quickEditFocus');
Route::post('/focus-tree/edit/{id}/delete/{focusid}','FocusTreeController@deleteFocus');
Route::post('/focus-tree/edit/{id}/importFromOldTool','FocusTreeController@importFromOldTool');
Route::post('/focus-tree/edit/{id}/importFromExistingFile','FocusTreeController@importFromExistingFile');
Route::post('/focus-tree/edit/{id}/importViaJSON','FocusTreeController@importViaJSON');
Route::post('/focus-tree/edit/{id}/globalMove','FocusTreeController@globalMove');
Route::post('/focus-tree/update/{id}','FocusTreeController@update');
Route::post('/focus-tree/edit/{id}/multiMove','FocusTreeController@multiMove');


//Event Related
Route::get('/events','EventsController@list');
Route::get('/events/view/{modid}','EventsController@view');
Route::get('/events/edit/{modid}','EventsController@edit');
Route::post('/events/edit/{modid}/add','EventsController@addEvent');
Route::post('/events/edit/{modid}/edit/{eventid}','EventsController@editEvent');
Route::get('/events/create','EventsController@showCreate');
Route::post('/events/create','EventsController@createEvents');
Route::post('/events/quickedit/{eventid}','EventsController@quickEditEvent');
Route::post('/events/quickedit/{eventid}/{outcomeid}','EventsController@quickEditEventOutcome');
Route::get('/events/delete/{eventid}/','EventsController@deleteEvent');
Route::get('/events/delete/{eventid}/{outcomeid}','EventsController@deleteEventOutcome');
Route::post('/events/edit/{modid}/outcome/add/{eventid}','EventsController@addOutcome');
Route::post('/events/edit/{modid}/outcome/edit/{outcomeid}','EventsController@editOutcome');

//Country Related
Route::group(['prefix' => 'country'], function () {
	Route::get('/', 'CountryController@list');
	Route::get('/view/{id}', 'CountryController@view');
	Route::get('/delete/{id}', 'CountryController@delete');
	Route::get('/edit/{id}', 'CountryController@edit');
	Route::get('/create', 'CountryController@showCreate');

	Route::post('/create', 'CountryController@create');
	Route::post('/edit/{id}', 'CountryController@update');
	Route::post('/edit/{id}/add-idea', 'CountryController@addIdea');
	Route::get('/edit/{id}/get-ideas', 'CountryController@getIdeas');
	Route::post('/get-leader', 'CountryController@getLeader');
	Route::post('/get-tabs', 'CountryController@getTabs');
	Route::post('/get-states', 'CountryController@getStates');
	Route::post('/delete-idea', 'CountryController@deleteIdea');
});

if(isBeta()){
	Route::group(['prefix' => 'ideas'], function () {
		Route::get('/', 'IdeaController@list');
		Route::get('/view/{id}', 'IdeaController@view');
		Route::get('/delete/{id}', 'IdeaController@delete');
		Route::get('/edit/{id}', 'IdeaController@edit');
		Route::get('/create', 'IdeaController@showCreate');

		Route::post('/create', 'IdeaController@create');
		Route::post('/edit/{id}/new/', 'IdeaController@addIdea');
		Route::post('/edit/{id}/import', 'IdeaController@import');
		Route::post('/edit/{id}/{ideaid}', 'IdeaController@editIdea');
		Route::post('/edit/{id}/{ideaid}/delete', 'IdeaController@deleteIdea');
	});
}

//Forum Related
Route::get('/forum', 'ForumController@index');
Route::get('/forum/{slug}', 'ForumController@forum');
Route::get('/forum/{slug}/{id}-{post_slug}', 'ForumController@forumPost');
Route::get('/forum/{slug}/{id}-{post_slug}/{action}/', 'ForumPostsController@forumPostAction');
Route::post('/forum/{slug}/{id}-{post_slug}/{action}/p/{action_id?}', 'ForumPostsController@forumPostAction');
Route::get('/forum/{slug}/{id}-{post_slug}/{action}/g/{action_id?}', 'ForumPostsController@forumPostAction');

Route::post('/forum/{slug}/{id}-{post_slug}', 'ForumCommentsController@commentPost');

Route::get('/forum/{slug}/create', 'ForumPostsController@create');
Route::post('/forum/{slug}/create', 'ForumPostsController@createPost');

//Api Stuff
Route::get('/api/v1/users', 'UserController@api');
Route::get('/api/v1/mod/add_role/{modid}/{userid}/{role}', 'ModController@apiAddRole');
Route::get('/api/v1/mod/remove_role/{modid}/{userid}', 'ModController@apiRemoveRole');
Route::get('/api/v1/events/{modid}', 'EventsController@api');


//Media
Route::get('media/get/{slashData?}', 'MediaController@get')->where('slashData', '(.*)');

/* ======
Images 
====== */

Route::group(['prefix' => 'image'], function(){
    // Route::get('/manager', ['as' => 'mediamanager.render', 'uses' => 'MediaController@renderMediaManager']);
    // Route::get('/manager/{path}', ['as' => 'mediamanager.renderPath', 'uses' => 'MediaController@renderMediaManagerPath']);
    Route::post('/delete/{id}', ['as' => 'media.delete', 'uses' => 'MediaController@deleteImage']);

    Route::post('/upload', ['as' => 'media.upload', 'uses' => 'MediaController@upload']);
    // Route::post('/upload-media-manager', ['as' => 'media.upload-media-manager', 'uses' => 'MediaController@mediaManagerUpload']);
    Route::get('/find/{id}', ['as' => 'media.find', 'uses' => 'MediaController@find']);
    Route::get('/find/{id}/{size}', ['as' => 'media.findSized', 'uses' => 'MediaController@findSized']);
    Route::get('/{path}/{filename}.{extension}', ['as' => 'media.findByName', 'uses' => 'MediaController@findByName']);
});

//Auth Related
Auth::routes();
//Route::get('/home', 'HomeController@index')->name('home');

//Voyager Related
// Route::group(['prefix' => 'admin'], function () {
//     Voyager::routes();
// });

app/Events.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Events extends Model
{
    public function mod(){
    	return $this->belongsTo(Mod::class);
    }

    public function outcomes(){
    	return $this->hasMany(EventOutcomes::class, 'event_id');
    }

    //Fix stupid url issues
    public function getEventGfxAttribute($value)
    {

        return str_replace('/home/hoimoddi/beta.hoi4modding.com', '', $value);
    }
}

resources/views/events/create.blade.php
@extends('templates.tool-focustree')

@section('title')
Create events - HOI4 Modding
@endsection


@section('description')
Create events for HOI IV
@endsection

@section('menu')
	@include('menus/generic')
@endsection

@section('content')
	@if(Auth::user())
		<div class="add_user_popup active create-focus" id="addUser">
			<div class="add_user_box stepped" data-step="1" data-last="3" data-is-last="0">
				<form method="POST" action="" enctype="multipart/form-data">
					<h3>Create New Events</h3>
					<div class="step step_1">
						{{ csrf_field() }}
						<h3>Select Mod Or Create A New One</h3>
						<p>
							<select name="mod_id" class="chooseModForEvent">
								<option value="createNewMod" data-has-events-language="false">Create New Mod</option>
								@if(!empty($mods))
									@foreach($mods as $mod)
										<?php
											$hasEventLangSet = 'false';
											if(!empty($mod->eventLanguage)){
												$hasEventLangSet = 'true';
											}
										?>
										<option value="{{$mod->id}}" data-has-events-language="{{$hasEventLangSet}}">{{$mod->mod_name}}</option>
									@endforeach
								@endif
							</select>
						</p>
					</div>
					<div class="step step_2 toggleNewModStep" data-new-mod-class="step step_2 toggleNewModStep" data-existing-mod-class="hidden_step toggleNewModStep">
						<div class="new-mod">
							<h3>New Mod Details</h3>
							<p><label>Mod Name</label></p>
							<p><input name="mod_name"></p>
							<p><label>Mod Description</label></p>
							<p><textarea name="mod_description"></textarea></p>
							<p><label>Mod Logo</label></p>
							<p><input name="mod_logo" type="file" accept="image/x-png"></p>
						</div>
						
					</div>
					<div class="step step_3 toggleNewModStep" data-new-mod-class="step step_3 toggleNewModStep" data-existing-mod-class="step step_2 toggleNewModStep">
						<div class="new-focus-tree">
							<p><label>Events Language</label></p>
							<select name="tree_lang">
								<option value="english">English</option>
								<option value="french">French</option>
								<option value="german">German</option>
								<option value="polish">Polish</option>
								<option value="braz_por">Portuguese</option>
								<option value="russian">Russian</option>
								<option value="spanish">Spanish</option>
							</select>
							<p><button class="generic_button">Submit</button></p>
						</div>
					</div>
					<div class="goToEvents" data-url="/events/edit/" style="display: none;">
						<a href="#" class="generic_button">Edit Events For This Mod</a>
					</div>
					<div class="stepper">
						<div class="prev">Back</div>
						<div class="next">Next</div>
					</div>
				</form>
			</div>
		</div>
	@else
		<div class="focus-panel create-focus">
			<div class="panel-head">
				Create Your Focus Tree
			</div>
			<div class="panel-body">
				<p>Logging in allows for automatic saving to the server, keeping multiple mods organised with ease, use of other elements of your mod (e.g. events), and much more.</p>
				<p>If you don't have an account, you can create one using the link below</p>
				<a href="/register" class="btn">Register</a>
				<p>Or Log In</p>
				 <form class="form-horizontal" method="POST" action="{{ route('login') }}">
                    {{ csrf_field() }}

                    <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                        <label for="email" class="col-md-4 control-label">E-Mail Address</label>

                        <div class="col-md-6">
                            <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required autofocus>

                            @if ($errors->has('email'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('email') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                        <label for="password" class="col-md-4 control-label">Password</label>

                        <div class="col-md-6">
                            <input id="password" type="password" class="form-control" name="password" required>

                            @if ($errors->has('password'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('password') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-6 col-md-offset-4">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="remember" {{ old('remember') ? 'checked' : '' }}> Remember Me
                                </label>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-8 col-md-offset-4">
                            <button type="submit" class="btn btn-primary">
                                Login
                            </button>

                            <a class="btn btn-link" href="{{ route('password.request') }}">
                                Forgot Your Password?
                            </a>
                        </div>
                    </div>
                </form>
			</div>
		</div>
			@endif
@endsection

resources/views/events/edit.blade.php
@extends('templates.tool-events')

@section('title')
{{$mod->mod_name}}'s Events - HOI4 Modding
@endsection


@section('description')
{{$mod->mod_description}}
@endsection

@section('menu')
	@include('menus/tool-events')
@endsection

@section('content')
<?php $eventNum = 1; $eventid = strtolower(preg_replace("/[^A-Za-z]/", '', $mod->mod_name)); ?>
	@foreach($events as $event)
		<div class="event-{{$event->event_type}} event-wrapper" data-event-id="{{$event->id}}">
			<div class="event-edit event">
				Edit
			</div>
			<div class="event-delete event">
				X
			</div>
			
			<div class="event-gfx">
				<img src="{{ storage( $event->event_gfx, 'public/storage') }}">
			</div>
			<div class="event-content">
				<div class="event-title">{{$event->event_title}}</div>
				<div class="event-description">
					{{$event->event_description}}
				</div>
				<div class="event-json"><?php
						$outcomes = $event->outcomes;
						$data = $event;
						unset($data['id']);
						unset($data['mod_id']);
						unset($data['outcomes']);
						echo $data;
					?></div>
				<div class="event-outcomes">
					@foreach($outcomes as $outcome)
						<div class="event-outcome" data-outcome-id="{{$outcome->id}}">
							<div class="event-edit">
								Edit
							</div>
							<div class="event-delete">
								X
							</div> 
							<span>{{$outcome->outcome_name}}</span>
							<div class="outcome_json">
								<?php 
									unset($outcome['id']);
									unset($outcome['event_id']);
									unset($outcome['created_at']);
									unset($outcome['updated_at']);
									echo $outcome; 
								?>
							</div>
						</div>
					@endforeach
					<div class="event-outcome-add">
						Add New Option
					</div>
				</div>
				<p><strong>Event ID:</strong> <em>{{$eventid.'.'.$eventNum}}</em></p>
			</div>
		</div>
		<?php $eventNum++; ?>
	@endforeach
@endsection

resources/views/events/list.blade.php
@extends('templates.tool')

@section('title')
Events List - HOI4 Modding
@endsection


@section('description')
Tools designed to make modding hearts of iron iv easy, and require no modding experience
@endsection

@section('menu')
	@include('menus/generic')
@endsection

@section('content')
	


	<p style="text-align: right"><a href="/events/create" class="generic_button">Create Events</a></p>
	@if($myMods)
		<h3>My Mods With Events</h3>
		<div class="modlist">
			@foreach($myMods as $mod)
				<div class="mod">
					<div class="image">
						<img src="{{ storage($mod->mod_logo, '/public/storage/') }}">
					</div>
					<div class="info">
						<a href="/mod/{{$mod->id}}"><h3>{{$mod->mod_name}}</h3></a>
						<div class="focuses">
							<div class="focustree">
								<a href="/events/view/{{$mod->id}}">{{$mod->mod_name}} - {{count($mod->events)}} events</a>
							</div>
						</div>
					</div>
				</div>
			@endforeach
		</div>
	@endif
@endsection

resources/views/events/view.blade.php
@extends('templates.tool')

@section('title')
{{$mod->mod_name}}'s Events - HOI4 Modding
@endsection


@section('description')
{{$mod->mod_description}}
@endsection

@section('menu')
	@include('menus/generic')
@endsection

@section('content')
	@foreach($events as $event)
		<div class="event-{{$event->event_type}}">
			<div class="event-gfx">
				<img src="{{ storage( $event->event_gfx, 'public/storage') }}">
			</div>
			<div class="event-content">
				<div class="event-title">
					{{$event->event_title}}
				</div>
				<div class="event-description">
					{{$event->event_description}}
				</div>
				<div class="event-outcomes">
					@foreach($event->outcomes as $outcome)
						<div class="event-outcome">
							{{$outcome->outcome_name}}
						</div>
					@endforeach
				</div>
			</div>
		</div>
	@endforeach
	@if($can_edit)
		<a href="/events/edit/{{$mod->id}}" class="focus-user-edit">Edit This Mods' Events</a>
	@endif
@endsection