routes/web.php
<?php
use App\CountryTags;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/tags.json', function(){
	return CountryTags::get();
});

Route::get('importTest', 'ModController@test');

//User Related
Route::get('/users', 'UserController@list');
Route::get('/users/{id}', 'UserController@view');
Route::get('/account', 'UserController@account');
Route::post('/account', 'UserController@updateAccount');
Route::get('/account/media', 'UserController@media');
Route::post('/account/media', 'UserController@mediaAction');
Route::get('/notifications', 'UserController@notifications');

//Mod Related
Route::get('/mod', 'ModController@list');
Route::get('/mod/{id}', 'ModController@view');
Route::post('/mod/{id}', 'ModController@editMod');
Route::get('/mod/{id}/export', 'ModController@export');
Route::post('/mod/{id}/delete', 'ModController@delete');

//Misc Tool Related
Route::get('/flag/', 'FlagController@viewCreate');
Route::post('/flag/create', ['as' => 'flag.create', 'uses' => 'FlagController@create']);
Route::post('/flag/download/{size}', ['as' => 'flag.download', 'uses' => 'FlagController@download']);

//Builder Related
Route::post('/builder', ['as' => 'builder.search', 'uses' => 'OutcomeController@search']);

//Focus Tree Related
Route::get('/focus-tree','FocusTreeController@list');
Route::get('/focus-tree/view/{id}','FocusTreeController@view');
Route::get('/focus-tree/delete/{id}','FocusTreeController@delete');
Route::get('/focus-tree/edit/{id}',['as' => 'tree.edit', 'uses' => 'FocusTreeController@edit']);
Route::get('/focus-tree/create','FocusTreeController@showCreate');
Route::post('/focus-tree/create','FocusTreeController@createFocusTree');
Route::post('/focus-tree/edit/{id}/add','FocusTreeController@createNewFocus');
Route::post('/focus-tree/edit/{id}/edit/{focus}','FocusTreeController@editFocus');
Route::post('/focus-tree/quickedit/{id}/edit/{focus}','FocusTreeController@quickEditFocus');
Route::post('/focus-tree/edit/{id}/delete/{focusid}','FocusTreeController@deleteFocus');
Route::post('/focus-tree/edit/{id}/importFromOldTool','FocusTreeController@importFromOldTool');
Route::post('/focus-tree/edit/{id}/importFromExistingFile','FocusTreeController@importFromExistingFile');
Route::post('/focus-tree/edit/{id}/importViaJSON','FocusTreeController@importViaJSON');
Route::post('/focus-tree/edit/{id}/globalMove','FocusTreeController@globalMove');
Route::post('/focus-tree/update/{id}','FocusTreeController@update');
Route::post('/focus-tree/edit/{id}/multiMove','FocusTreeController@multiMove');


//Event Related
Route::get('/events','EventsController@list');
Route::get('/events/view/{modid}','EventsController@view');
Route::get('/events/edit/{modid}','EventsController@edit');
Route::post('/events/edit/{modid}/add','EventsController@addEvent');
Route::post('/events/edit/{modid}/edit/{eventid}','EventsController@editEvent');
Route::get('/events/create','EventsController@showCreate');
Route::post('/events/create','EventsController@createEvents');
Route::post('/events/quickedit/{eventid}','EventsController@quickEditEvent');
Route::post('/events/quickedit/{eventid}/{outcomeid}','EventsController@quickEditEventOutcome');
Route::get('/events/delete/{eventid}/','EventsController@deleteEvent');
Route::get('/events/delete/{eventid}/{outcomeid}','EventsController@deleteEventOutcome');
Route::post('/events/edit/{modid}/outcome/add/{eventid}','EventsController@addOutcome');
Route::post('/events/edit/{modid}/outcome/edit/{outcomeid}','EventsController@editOutcome');

//Country Related
Route::group(['prefix' => 'country'], function () {
	Route::get('/', 'CountryController@list');
	Route::get('/view/{id}', 'CountryController@view');
	Route::get('/delete/{id}', 'CountryController@delete');
	Route::get('/edit/{id}', 'CountryController@edit');
	Route::get('/create', 'CountryController@showCreate');

	Route::post('/create', 'CountryController@create');
	Route::post('/edit/{id}', 'CountryController@update');
	Route::post('/edit/{id}/add-idea', 'CountryController@addIdea');
	Route::get('/edit/{id}/get-ideas', 'CountryController@getIdeas');
	Route::post('/get-leader', 'CountryController@getLeader');
	Route::post('/get-tabs', 'CountryController@getTabs');
	Route::post('/get-states', 'CountryController@getStates');
	Route::post('/delete-idea', 'CountryController@deleteIdea');
});

if(isBeta()){
	Route::group(['prefix' => 'ideas'], function () {
		Route::get('/', 'IdeaController@list');
		Route::get('/view/{id}', 'IdeaController@view');
		Route::get('/delete/{id}', 'IdeaController@delete');
		Route::get('/edit/{id}', 'IdeaController@edit');
		Route::get('/create', 'IdeaController@showCreate');

		Route::post('/create', 'IdeaController@create');
		Route::post('/edit/{id}/new/', 'IdeaController@addIdea');
		Route::post('/edit/{id}/import', 'IdeaController@import');
		Route::post('/edit/{id}/{ideaid}', 'IdeaController@editIdea');
		Route::post('/edit/{id}/{ideaid}/delete', 'IdeaController@deleteIdea');
	});
}

//Forum Related
Route::get('/forum', 'ForumController@index');
Route::get('/forum/{slug}', 'ForumController@forum');
Route::get('/forum/{slug}/{id}-{post_slug}', 'ForumController@forumPost');
Route::get('/forum/{slug}/{id}-{post_slug}/{action}/', 'ForumPostsController@forumPostAction');
Route::post('/forum/{slug}/{id}-{post_slug}/{action}/p/{action_id?}', 'ForumPostsController@forumPostAction');
Route::get('/forum/{slug}/{id}-{post_slug}/{action}/g/{action_id?}', 'ForumPostsController@forumPostAction');

Route::post('/forum/{slug}/{id}-{post_slug}', 'ForumCommentsController@commentPost');

Route::get('/forum/{slug}/create', 'ForumPostsController@create');
Route::post('/forum/{slug}/create', 'ForumPostsController@createPost');

//Api Stuff
Route::get('/api/v1/users', 'UserController@api');
Route::get('/api/v1/mod/add_role/{modid}/{userid}/{role}', 'ModController@apiAddRole');
Route::get('/api/v1/mod/remove_role/{modid}/{userid}', 'ModController@apiRemoveRole');
Route::get('/api/v1/events/{modid}', 'EventsController@api');


//Media
Route::get('media/get/{slashData?}', 'MediaController@get')->where('slashData', '(.*)');

/* ======
Images 
====== */

Route::group(['prefix' => 'image'], function(){
    // Route::get('/manager', ['as' => 'mediamanager.render', 'uses' => 'MediaController@renderMediaManager']);
    // Route::get('/manager/{path}', ['as' => 'mediamanager.renderPath', 'uses' => 'MediaController@renderMediaManagerPath']);
    Route::post('/delete/{id}', ['as' => 'media.delete', 'uses' => 'MediaController@deleteImage']);

    Route::post('/upload', ['as' => 'media.upload', 'uses' => 'MediaController@upload']);
    // Route::post('/upload-media-manager', ['as' => 'media.upload-media-manager', 'uses' => 'MediaController@mediaManagerUpload']);
    Route::get('/find/{id}', ['as' => 'media.find', 'uses' => 'MediaController@find']);
    Route::get('/find/{id}/{size}', ['as' => 'media.findSized', 'uses' => 'MediaController@findSized']);
    Route::get('/{path}/{filename}.{extension}', ['as' => 'media.findByName', 'uses' => 'MediaController@findByName']);
});

//Auth Related
Auth::routes();
//Route::get('/home', 'HomeController@index')->name('home');

//Voyager Related
// Route::group(['prefix' => 'admin'], function () {
//     Voyager::routes();
// });

app/Focuses.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Focuses extends Model
{
	//Fix stupid url issues
    public function getFocusGfxAttribute($value)
    {

        return str_replace('/home/hoimoddi/beta.hoi4modding.com', '', $value);
    }
}

app/Http/Controllers/FocusTreeController.php
<?php

namespace App\Http\Controllers;

use App\FocusTree;
use App\Mod;
use App\User;
use App\UserMod;
use App\Focuses;
use App\Imports;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Input;
use Illuminate\Http\Request;
use Illuminate\Http\UploadedFile;
use mysqli;
use Storage;
use App\Http\Controllers\ModController;

class FocusTreeController extends Controller
{
	private $focusTreeInternalIds = [];
	/**
	 * Show the profile for the given user.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function view($id)
	{
		$focusTree = FocusTree::findOrFail($id);
		$can_edit = false;
		if(Auth::user()){
			foreach($focusTree->mod->users as $user){
				if($user->id == Auth::user()->id){
					$can_edit = true;
				}
			}
			if(Auth::user()->role_id == 1){
				$can_edit = true;
			}
		}

		$this->moveFocusesToCorrectPosition($focusTree->focuses);

		foreach($focusTree->focuses as $focus){
			if(!empty($focus->external_id)){
				$this->focusTreeInternalIds[$focus->external_id] = $focus;
			}
		}
		foreach($focusTree->focuses as $focus){


			$pr = $this->stripMultiRelations($focus->focus_prerequisite);
			$me = $this->stripMultiRelations($focus->focus_mutually_exclusive);

			if(!empty($pr)){
				//If it isn't using internal IDs only, then we cry
				if(((int) $pr === 0) && !empty($pr)){
					$focus->focus_prerequisite = $this->externalIdToInternalId($focus->focus_prerequisite);
				}
			}
			if(!empty($me) ){
				//If it isn't using internal IDs only, then we cry
				if(((int) $me === 0) && !empty($me)){
					$focus->focus_mutually_exclusive = $this->externalIdToInternalId($focus->focus_mutually_exclusive);
				}
			}

			$focus->save();

		}
		return view('focustree/view', ['tree' => $focusTree, 'can_edit' => $can_edit, 'is_editable' => false]);
	}

	public function update(Request $request, $id){
		$tree = FocusTree::findOrFail($id);
		if(!empty($request->country_tag)){
			$tree->country_tag = $request->country_tag;
		}
		if(!empty($request->tree_id)){
			$tree->tree_id = $request->tree_id;
		}
		if(!empty($request->lang)){
			$tree->lang = $request->lang;
		}
		$tree->save();
		return redirect()->back()->with('success', 'Successfully updated focus tree for '.$tree->country_tag);
	}

	public function delete($id)
	{
		$tree = FocusTree::findOrFail($id);
		$name = $tree->country_tag;
		$modid = $tree->mod->id;
		$can_edit = false;
		$check = UserMod::where('mod_id', '=', $modid)->where('user_id', '=', Auth::user()->id)->first();
		if(strtolower($check->role) != 'creator'){
			return redirect()->back()->with('error', 'Only the creator of the parent mod can delete this');
		}
		if(Auth::user()){
			foreach($tree->mod->users as $user){
				if($user->id == Auth::user()->id){
					$can_edit = true;
				}
			}
			if(Auth::user()->role_id == 1){
				$can_edit = true;
			}
		}
		if($can_edit){
			foreach($tree->focuses as $focus){
				$focus->delete();
			}
			$tree->delete();
			\Session::flash('success', 'You have successfully deleted the focus tree for '.$name);
		}else{
			\Session::flash('error', 'You do not have permission to perform this action');
		}
		return redirect('/mod/'.$modid);
	}

	public function list()
	{
		
		if(Auth::user()){
			$myMods = Auth::user()->mods;
		}else{
			$myMods = null;
		}
		return view('focustree/list', ['myMods' => $myMods]);
	}

	public function showCreate(){
		if(Auth::user()){
			$id = Auth::user()->id;
			$mods = User::findOrFail($id)->mods;
		}else{
			$mods = [];
		}
		return view('focustree/create', ['mods' => $mods, 'can_edit' => true, 'is_editable' => false]);
	}

	public function createFocusTree(Request $request){
		if(Input::get('mod_id') == 'createNewMod'){
			$controller = new ModController();
			$modid = $controller->createMod($request);
		}else{
			$modid = Input::get('mod_id');
		}
		//Create the focus tree
		$id = \DB::table('focus_trees')->insertGetId(
			[
				'mod_id' => $modid,
				'country_tag' => Input::get('tree_country'),
				'tree_id' => Input::get('tree_id'),
				'lang' => Input::get('tree_lang'),
				'created_at' => date('Y-m-d G:i:s'),
				'updated_at' => date('Y-m-d G:i:s')
			]
		);
		$mod = Mod::find($modid);
		$mod->has_focus_tree = 1;
		$mod->save();
		return redirect('/focus-tree/edit/'.$id);
	}

	public function moveFocusesToCorrectPosition($focuses){
		$focusList = [];
		$total = $focuses->count();

		$fixed = 0;
		$attempts = 0;
		while($fixed < $total && $attempts < ($fixed * $fixed * $fixed * $fixed * $fixed * $fixed)){
			foreach($focuses as $focus){
				if(empty($focus->focus_relative_position)){
					if(!isset($focusList[$focus->external_id])){
						$focusList[$focus->external_id] = ['x' => $focus->focus_x, 'y' => $focus->focus_y];
						$fixed++;
					}
				}else{
					if(isset($focusList[$focus->focus_relative_position])){
						$rel = $focusList[$focus->focus_relative_position];
						$focus->focus_x = $focus->focus_x + $rel['x'];
						$focus->focus_y = $focus->focus_y + $rel['y'];
						$focus->focus_relative_position = '';
						$focus->save();
					}
				}
			}
			$attempts++;
		}
	}

	public function edit($id){
		if(Auth::user()){
			$focusTree = FocusTree::findOrFail($id);
			$canEdit = $this->canUserEdit($id);
			if($canEdit){

				$this->moveFocusesToCorrectPosition($focusTree->focuses);

				foreach($focusTree->focuses as $focus){
					if(!empty($focus->external_id)){
						$this->focusTreeInternalIds[$focus->external_id] = $focus;
					}
				}

				foreach($focusTree->focuses as $focus){


					$pr = $this->stripMultiRelations($focus->focus_prerequisite);
					$me = $this->stripMultiRelations($focus->focus_mutually_exclusive);

					if(!empty($pr)){
						//If it isn't using internal IDs only, then we cry
						if(((int) $pr === 0) && !empty($pr)){
							$focus->focus_prerequisite = $this->externalIdToInternalId($focus->focus_prerequisite);
						}
					}
					if(!empty($me) ){
						//If it isn't using internal IDs only, then we cry
						if(((int) $me === 0) && !empty($me)){
							$focus->focus_mutually_exclusive = $this->externalIdToInternalId($focus->focus_mutually_exclusive);
						}
					}

					$focus->save();

				}

				return view('focustree/edit', ['tree' => $focusTree, 'can_edit' => $canEdit, 'is_editable' => true, 'rawtext' => $this->getFocusTreeOutput($focusTree)]);
			}else{
				die("You can't edit this");
			}
		}else{
			return redirect('/login');
		}
	}

	public function getFocusRelativePosition($externalID, $x, $y, $count = 0){
		$relatedFocus = null;
		if(isset($this->focusTreeInternalIds[$externalID]) && $count < 999999){
			$relatedFocus = $this->focusTreeInternalIds[$externalID];
			if(!empty($relatedFocus->focus_relative_position)){
				$relationFocus = $this->getFocusRelativePosition($relatedFocus->focus_relative_position, $relatedFocus->focus_x, $relatedFocus->focus_y, ($count + 1));
				$newX = $relationFocus[0];
				$newY = $relationFocus[1];
			}else{
				$newX = ($relatedFocus->focus_x + $x);
				$newY = ($relatedFocus->focus_y + $y);
			}
		}else{
			$newX = $x;
			$newY = $y;
		}
		return array($newX, $newY);
	}

	//Replace all external IDs in the string with internal IDs
	public function externalIdToInternalId($string){
		$editingString = $string;
		$readyToSplit = str_replace('&&', '||', $string);
		$array = explode('||', $readyToSplit);

		foreach(array_filter($array) as $externalID){
			if(isset($this->focusTreeInternalIds[$externalID])){
				$editingString = str_replace($externalID, $this->focusTreeInternalIds[$externalID]->id, $editingString);
			}else{
				$editingString = str_replace([$externalID.'&&', $externalID.'||'], '', $editingString);
				$editingString = str_replace($externalID, '', $editingString);
			}
		}
		return $editingString;
	}

	public function stripMultiRelations($unformattedRelation){
		return str_replace(['&&', '||'], '', $unformattedRelation);
	}

	public function globalMove(Request $request, $treeid){
		if(Auth::user()){
			$canEdit = $this->canUserEdit($treeid);
			if($canEdit){
				$tree = FocusTree::find($treeid);
				$distance = $request->input('distance');
				$axis = $request->input('axis');
				foreach($tree->focuses as $focus){
					if($axis == 'x'){
						if(($focus->focus_x + $distance) >= 0){
							$focus->focus_x = ($focus->focus_x + $distance);
						}else{
							$focus->focus_x = 0;
						}
					}
					if($axis == 'y'){
						if(($focus->focus_y + $distance) >= 0){
							$focus->focus_y = ($focus->focus_y + $distance);
						}else{
							$focus->focus_y = 0;
						}
					}
					$focus->save();
				}
				return redirect(route('tree.edit', ['id' => $treeid]));
			}else{
				die('<script>parent.NFunauthorisedUser();</script>');
			}
		}else{
			die('<script>parent.NFsessionExpired();</script>');
		}
	}

	public function multiMove(Request $request, $treeid){
		if(Auth::user()){
			$canEdit = $this->canUserEdit($treeid);
			if($canEdit){
				$focuses = Focuses::where('focus_tree_id', '=', $treeid)->whereIn('id', $request->focus)->get();
				$distance = $request->input('distance');
				$axis = $request->input('axis');
				foreach($focuses as $focus){
					if($axis == 'x'){
						if(($focus->focus_x + $distance) >= 0){
							$focus->focus_x = ($focus->focus_x + $distance);
						}else{
							$focus->focus_x = 0;
						}
					}
					if($axis == 'y'){
						if(($focus->focus_y + $distance) >= 0){
							$focus->focus_y = ($focus->focus_y + $distance);
						}else{
							$focus->focus_y = 0;
						}
					}
					$focus->save();
				}
				return redirect(route('tree.edit', ['id' => $treeid]));
			}else{
				die('<script>parent.NFunauthorisedUser();</script>');
			}
		}else{
			die('<script>parent.NFsessionExpired();</script>');
		}
	}

	public function createNewFocus(Request $request, $treeid){
		if(Auth::user()){
			$canEdit = $this->canUserEdit($treeid);
			if($canEdit){
				$errors = array();
				if($request->input('chosen_gfx') == 'custom'){
					//Upload file, and add it

resources/views/focustree/create.blade.php
@extends('templates.tool-focustree')

@section('title')
Create a focus tree - HOI4 Modding
@endsection


@section('description')
Create a focus tree for HOI IV
@endsection

@section('menu')
	@include('menus/generic')
@endsection

@section('content')
	@if(Auth::user())
		<div class="add_user_popup active create-focus" id="addUser">
			<div class="add_user_box stepped" data-step="1" data-last="3" data-is-last="0">
				<form method="POST" action="" enctype="multipart/form-data">
					<h3>Create New Focus Tree</h3>
					<div class="step step_1">
						{{ csrf_field() }}
						<h3>Select Mod Or Create A New One</h3>
						<p>
							<select name="mod_id">
								<option value="createNewMod">Create New Mod</option>
								@if(!empty($mods))
									@foreach($mods as $mod)
										<option value="{{$mod->id}}">{{$mod->mod_name}}</option>
									@endforeach
								@endif
							</select>
						</p>
					</div>
					<div class="step step_2 toggleNewModStep" data-new-mod-class="step step_2 toggleNewModStep" data-existing-mod-class="hidden_step toggleNewModStep">
						<div class="new-mod">
							<h3>New Mod Details</h3>
							<p><label>Mod Name</label></p>
							<p><input name="mod_name"></p>
							<p><label>Mod Description</label></p>
							<p><textarea name="mod_description"></textarea></p>
							<p><label>Mod Logo</label></p>
							<p><input name="mod_logo" type="file" accept="image/x-png"></p>
						</div>
						
					</div>
					<div class="step step_3 toggleNewModStep" data-new-mod-class="step step_3 toggleNewModStep" data-existing-mod-class="step step_2 toggleNewModStep">
						<div class="new-focus-tree">
							<p><label>Focus Tree ID</label></p>
							<p><input name="tree_id"></p>
							<p><label>Focus Tree Language</label></p>
							<select name="tree_lang">
								<option value="english">English</option>
								<option value="french">French</option>
								<option value="german">German</option>
								<option value="polish">Polish</option>
								<option value="braz_por">Portuguese</option>
								<option value="russian">Russian</option>
								<option value="spanish">Spanish</option>
							</select>
							<p><label>Focus Tree Country</label></p>
							<p><input name="tree_country" class="choose-country" id="tree_country"></p>
							<p><button class="generic_button">Submit</button></p>
						</div>
					</div>
					<div class="stepper">
						<div class="prev">Back</div>
						<div class="next">Next</div>
					</div>
				</form>
			</div>
		</div>
	@else
		<div class="focus-panel create-focus">
			<div class="panel-head">
				Create Your Focus Tree
			</div>
			<div class="panel-body">
				<p>Logging in allows for automatic saving to the server, keeping multiple mods organised with ease, use of other elements of your mod (e.g. events), and much more.</p>
				<p>If you don't have an account, you can create one using the link below</p>
				<a href="/register" class="btn">Register</a>
				<p>Or Log In</p>
				 <form class="form-horizontal" method="POST" action="{{ route('login') }}">
                    {{ csrf_field() }}

                    <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                        <label for="email" class="col-md-4 control-label">E-Mail Address</label>

                        <div class="col-md-6">
                            <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required autofocus>

                            @if ($errors->has('email'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('email') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                        <label for="password" class="col-md-4 control-label">Password</label>

                        <div class="col-md-6">
                            <input id="password" type="password" class="form-control" name="password" required>

                            @if ($errors->has('password'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('password') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-6 col-md-offset-4">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="remember" {{ old('remember') ? 'checked' : '' }}> Remember Me
                                </label>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-8 col-md-offset-4">
                            <button type="submit" class="btn btn-primary">
                                Login
                            </button>

                            <a class="btn btn-link" href="{{ route('password.request') }}">
                                Forgot Your Password?
                            </a>
                        </div>
                    </div>
                </form>
			</div>
		</div>
			@endif
@endsection

resources/views/focustree/edit.blade.php
@extends('templates.tool-focustree')

@section('title')
{{$tree->mod->mod_name}}'s Focus Tree for {{$tree->country_tag}} - HOI4 Modding
@endsection


@section('description')
{{$tree->mod->mod_description}}
@endsection

@section('menu')
	@include('menus/tool-focus')
@endsection

@section('content')
	@foreach($tree->focuses as $focus)
		<div class="focus-content" data-x="{{$focus->focus_x}}" data-y="{{$focus->focus_y}}" data-focus-id="{{$focus->id}}">
			<img src="{{ storage( $focus->focus_gfx, 'public/storage') }}" class="focus-image">
			<p class="focus-title">{{$focus->focus_title}}</p>
			<div class="focus-description">
				<p class="edit-focus">Edit</p>
				<div>{{$focus->focus_description}}</div>
			</div>
			<div class="focus-json">
				<?php
					$data = $focus;
					unset($data['id']);
					unset($data['focus_tree_id']);
					unset($data['focus_title']);
					unset($data['focus_description']);
					unset($data['focus_gfx']);
					unset($data['created_at']);
					unset($data['updated_at']);
					echo $data;
				?>
			</div>
		</div>
	@endforeach
	<div class="focus-tree-raw-wrapper">
		<div class="focus-tree-raw closed"><div><button class="generic_button showFocusError">Only show errors</button></div>{!! $rawtext !!}</div>
		<div class="focus-tree-raw-toggle"><i class="fa fa-chevron-up"></i></div>
	</div>
@endsection

resources/views/focustree/list.blade.php
@extends('templates.tool')

@section('title')
Focus Tree List - HOI4 Modding
@endsection


@section('description')
Tools designed to make modding hearts of iron iv easy, and require no modding experience
@endsection

@section('menu')
	@include('menus/generic')
@endsection

@section('content')
	<p style="text-align: right"><a href="/focus-tree/create" class="generic_button">Create Focus Tree</a></p>
	@if($myMods)
		<h3>My Mods With Focus Trees</h3>
		<div class="modlist">
			@foreach($myMods as $mod)
				<div class="mod">
					<div class="image">
						<img src="{{ storage($mod->mod_logo, '/public/storage/') }}">
					</div>
					<div class="info">
						<a href="/mod/{{$mod->id}}"><h3>{{$mod->mod_name}}</h3></a>
						<div class="focuses">
							<p>Focus Trees</p>
							@foreach($mod->focusTrees as $tree)
								<div class="focustree">
									<a href="/focus-tree/view/{{$tree->id}}">{{$tree->tree_id}} ({{$tree->country_tag}}) - {{count($tree->focuses)}} focuses</a>
								</div>
							@endforeach
						</div>
					</div>
				</div>
			@endforeach
		</div>
	@endif
@endsection

resources/views/focustree/view.blade.php
@extends('templates.tool-focustree')

@section('title')
{{$tree->mod->mod_name}}'s Focus Tree for {{$tree->country_tag}} - HOI4 Modding
@endsection


@section('description')
{{$tree->mod->mod_description}}
@endsection

@section('menu')
	@include('menus/generic')
@endsection

@section('content')
	@foreach($tree->focuses as $focus)
		<div class="focus-content" data-focus-id="{{$focus->id}}" data-x="{{$focus->focus_x}}" data-y="{{$focus->focus_y}}">
			<img src="{{ storage( $focus->focus_gfx, 'public/storage') }}">
			<p class="focus-title">{{$focus->focus_title}}</p>
			<div class="focus-description">{{$focus->focus_description}}</div>
			<div class="focus-json">
				<?php
					$data = $focus;
					unset($data['id']);
					unset($data['focus_tree_id']);
					unset($data['focus_title']);
					unset($data['focus_description']);
					unset($data['focus_gfx']);
					unset($data['created_at']);
					unset($data['updated_at']);
					echo $data;
				?>
			</div>
		</div>
	@endforeach
	@if($can_edit)
		<a href="/focus-tree/edit/{{$tree->id}}" class="focus-user-edit">Edit This Tree</a>
	@endif
@endsection